import{careers,scholarships}from'../data/data';import{get,set,del,clear}from'../utils/storage';
export const auth={users:()=>get('users',[{id:'1',name:'Keerthana',email:'student@eduguide.ai',password:'student123',role:'student',status:'Active'},{id:'2',name:'EduGuide Parent',email:'parent@eduguide.ai',password:'parent123',role:'parent',status:'Active'},{id:'3',name:'EduGuide Admin',email:'admin@eduguide.ai',password:'admin123',role:'admin',status:'Active'}]),login:(e,p)=>{const u=auth.users().find(x=>x.email.toLowerCase()===e.toLowerCase()&&x.password===p);if(!u)throw Error('Invalid email or password.');if(u.status==='Inactive')throw Error('Account inactive.');const s={id:u.id,name:u.name,email:u.email,role:u.role};set('user',s);return s},register:d=>{const u={id:crypto.randomUUID(),...d,status:'Active'};if(auth.users().some(x=>x.email===d.email))throw Error('Email already registered.');set('users',[...auth.users(),u]);set('user',{id:u.id,name:u.name,email:u.email,role:u.role});return u},logout:()=>del('user'),current:()=>get('user')};
export const careerService={all:()=>get('careers',careers),one:id=>careerService.all().find(x=>x.id===id),save:x=>set('careers',[...careerService.all().filter(y=>y.id!==x.id),x]),remove:id=>set('careers',careerService.all().filter(x=>x.id!==id))};
export const scholarshipService={all:()=>get('scholarships',scholarships),one:id=>scholarshipService.all().find(x=>x.id===id),saved:()=>get('saved_scholarships',[]),toggle:id=>{const a=scholarshipService.saved();set('saved_scholarships',a.includes(id)?a.filter(x=>x!==id):[...a,id])},save:x=>set('scholarships',[...scholarshipService.all().filter(y=>y.id!==x.id),x]),remove:id=>set('scholarships',scholarshipService.all().filter(x=>x.id!==id))};
export const profileService={get:()=>get('profile',{name:'Keerthana',state:'Karnataka',city:'Bengaluru',degree:'B.Tech',branch:'Computer Science and Engineering',year:'4th Year',graduationYear:'2027',interests:['AI/ML','Software Development','Data Analytics'],skills:['Python','JavaScript','React','SQL','Machine Learning','Problem Solving'],goals:['Internship','Job','Skill Development','Career Exploration']}),save:p=>set('profile',p),permissions:()=>get('permissions',{interests:true,roadmap:true,goals:true,ai:false,notes:false}),savePermissions:p=>set('permissions',p)};
export const deadlineService={all:()=>get('deadlines',[{id:'d1',title:'Scholarship Application',category:'Scholarship',date:'2026-10-15',priority:'High',notes:'Demo deadline'},{id:'d2',title:'Internship Application',category:'Internship',date:'2026-10-20',priority:'Medium',notes:'Prepare resume'},{id:'d3',title:'Exam Registration',category:'Exam',date:'2026-10-25',priority:'High',notes:'Check portal'}]),save:x=>set('deadlines',[...deadlineService.all().filter(y=>y.id!==x.id),x]),remove:id=>set('deadlines',deadlineService.all().filter(x=>x.id!==id))};
export const studyService={goals:()=>get('goals',[]),save:g=>set('goals',[...studyService.goals().filter(x=>x.id!==g.id),g]),remove:id=>set('goals',studyService.goals().filter(x=>x.id!==id)),plans:()=>get('plans',[]),savePlan:p=>set('plans',[...studyService.plans().filter(x=>x.id!==p.id),p]),removePlan:id=>set('plans',studyService.plans().filter(x=>x.id!==id))};
export const aiService=async q=>{await new Promise(r=>setTimeout(r,350));q=q.toLowerCase();if(q.includes('career'))return'Explore careers by comparing your interests, skills, learning path and project opportunities. For CSE, Software Engineering, Data, AI/ML, Cybersecurity, Cloud and Networking are common paths to investigate.';if(q.includes('scholar'))return'Use the Scholarship Finder to filter by state, education level, amount and deadline. The Profile Match Estimate is only a demo estimate; verify official eligibility before applying.';if(q.includes('study')||q.includes('plan'))return'Choose one measurable topic, study in focused blocks, practise with questions, build a small project and review your progress every few days.';if(q.includes('ai')||q.includes('machine'))return'Beginner AI/ML path: Python → statistics → NumPy/Pandas → machine learning → evaluation → deep learning → projects → deployment.';if(q.includes('placement')||q.includes('interview'))return'For placements, strengthen DSA, one programming language, SQL, CS fundamentals, your projects and communication. Practise explaining each project clearly.';return'I can help with careers, scholarships, study planning, AI/ML, placements and academic planning. Tell me what you are working toward.'};
export const appData={clear};
