import{Link}from'react-router-dom';import{profileService,auth,careerService,scholarshipService}from'../services/services';import{resources}from'../data/data';import{Card,Badge,Button,Field,Modal}from'../components/UI';import{useState}from'react';
export function ParentDashboard(){const p=profileService.get(),per=profileService.permissions();return <div><h1>Welcome to EduGuide Parent 👋</h1><p>Understand modern careers and view only information the student chooses to share.</p><div className="cards3">{[['/parent/careers','🎓','Career Opportunities'],['/parent/ai','🤖','AI Guidance'],['/parent/resources','📚','Useful Resources'],['/parent/shared-progress','👨‍👩‍👧','Shared Progress']].map(x=><Link key={x[0]} to={x[0]}><Card><span className="emoji">{x[1]}</span><h3>{x[2]}</h3><p>Open this parent-friendly section.</p></Card></Link>)}</div><Card><h3>Sharing status</h3>{Object.entries({interests:'Career interests',roadmap:'Roadmap progress',goals:'Academic goals',ai:'AI conversations',notes:'Private notes'}).map(([k,v])=><p key={k}>{v}: <b>{per[k]?'Shared':'Private'}</b></p>)}</Card></div>}
export function ParentCareers(){const a=[['🤖','What is AI?','AI helps computers perform tasks such as recognizing patterns, understanding language and learning from data.'],['💻','What is Software Engineering?','Software engineers build and maintain applications, websites, services and systems.'],['🛡️','What is Cybersecurity?','Cybersecurity protects computers, networks and information from misuse or attacks.'],['📊','What is Data Science?','Data science combines data, statistics and programming to discover useful patterns.'],['🔬','What is Research?','Research explores questions, tests ideas and creates new knowledge or technology.'],['☁️','What are technology careers?','Technology includes software, data, AI, cloud, networking, design, product and security roles.']];return <div><h1>Career Explorer</h1><p>Simple explanations without unnecessary jargon.</p><div className="cards3">{a.map(x=><Card key={x[1]}><span className="emoji">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></Card>)}</div></div>}
export function ParentAI(){return <div><h1>AI Guidance</h1><p>Ask about modern careers in simple language.</p><Card><p><b>Example:</b> “My child likes computers. What careers are available?”</p><Link className="btn primary" to="/student/ai">Open AI simulation</Link></Card></div>}
export function ParentResources(){return <div><h1>Useful Resources</h1><div className="cards3">{resources.slice(0,12).map(r=><Card key={r.id}><Badge>{r.category}</Badge><h3>{r.title}</h3><a className="link" href={r.url} target="_blank">Open →</a></Card>)}</div></div>}
export function Shared(){const p=profileService.get(),x=profileService.permissions();return <div><h1>Shared Progress</h1><p>Only permitted information is shown.</p><div className="cards3">{x.interests&&<Card><h3>Career Interests</h3><p>{p.interests?.join(', ')}</p></Card>}{x.goals&&<Card><h3>Goals</h3><p>{p.goals?.join(', ')}</p></Card>}{x.roadmap&&<Card><h3>Roadmap</h3><p>Student has enabled roadmap sharing.</p></Card>}</div></div>}
export function AdminDashboard(){return <div><h1>Admin Dashboard</h1><div className="cards3">{[['👩‍🎓','Students',auth.users().filter(x=>x.role==='student').length],['👨‍👩‍👧','Parents',auth.users().filter(x=>x.role==='parent').length],['💰','Scholarships',scholarshipService.all().length],['🎓','Careers',careerService.all().length],['📚','Resources',resources.length]].map(x=><Card key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><strong className="score">{x[2]}</strong></Card>)}</div></div>}
export function AdminUsers(){const[,r]=useState(0);const users=auth.users();return <div><h1>User Management</h1><Card>{users.map(u=><div className="row" key={u.id}><div><b>{u.name}</b><small>{u.email} • {u.role}</small></div><Button variant="soft" onClick={()=>{const n=users.map(x=>x.id===u.id?{...x,status:x.status==='Active'?'Inactive':'Active'}:x);localStorage.setItem('eduguide_users',JSON.stringify(n));r(x=>x+1)}}>{u.status}</Button></div>)}</Card></div>}
export function AdminCareers(){const[,r]=useState(0);const cs=careerService.all();return <div><h1>Career Management</h1><Card>{cs.map(c=><div className="row" key={c.id}><div><b>{c.icon} {c.name}</b><small>{c.category}</small></div><Button variant="danger" onClick={()=>{careerService.remove(c.id);r(x=>x+1)}}>Delete</Button></div>)}</Card></div>}
export function AdminScholarships(){const[,r]=useState(0);const ss=scholarshipService.all();return <div><h1>Scholarship Management</h1><Card>{ss.map(s=><div className="row" key={s.id}><div><b>{s.name}</b><small>{s.provider} • {s.deadline}</small></div><Button variant="danger" onClick={()=>{scholarshipService.remove(s.id);r(x=>x+1)}}>Delete</Button></div>)}</Card></div>}
export function AdminResources(){return <div><h1>Resource Management</h1><p>Local resource catalog uses known public resources.</p></div>}
